--liquibase formatted sql
--changeset migration-team:1
--comment: Spring Integration JDBC Message Store Schema for PostgreSQL v6.5+

-- Sequence for message ordering (FIFO)
CREATE SEQUENCE IF NOT EXISTS INT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;

-- Core message table for claim-check pattern
CREATE TABLE IF NOT EXISTS INT_MESSAGE (
    MESSAGE_ID CHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    MESSAGE_BYTES BYTEA,
    CONSTRAINT INT_MESSAGE_PK PRIMARY KEY (MESSAGE_ID, REGION)
);

CREATE INDEX IF NOT EXISTS INT_MESSAGE_IX1 ON INT_MESSAGE (CREATED_DATE);

-- Group to message mapping for aggregators
CREATE TABLE IF NOT EXISTS INT_GROUP_TO_MESSAGE (
    GROUP_KEY CHAR(36) NOT NULL,
    MESSAGE_ID CHAR(36) NOT NULL,
    REGION VARCHAR(100),
    CONSTRAINT INT_GROUP_TO_MESSAGE_PK PRIMARY KEY (GROUP_KEY, MESSAGE_ID, REGION)
);

-- Message group table for aggregators
CREATE TABLE IF NOT EXISTS INT_MESSAGE_GROUP (
    GROUP_KEY CHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    GROUP_CONDITION VARCHAR(255),
    COMPLETE BIGINT,
    LAST_RELEASED_SEQUENCE BIGINT,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP DEFAULT NULL,
    CONSTRAINT INT_MESSAGE_GROUP_PK PRIMARY KEY (GROUP_KEY, REGION)
);

-- Distributed lock table
CREATE TABLE IF NOT EXISTS INT_LOCK (
    LOCK_KEY CHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    CLIENT_ID CHAR(36),
    CREATED_DATE TIMESTAMP NOT NULL,
    EXPIRED_AFTER TIMESTAMP NOT NULL,
    CONSTRAINT INT_LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
);

-- Channel message table
CREATE TABLE IF NOT EXISTS INT_CHANNEL_MESSAGE (
    MESSAGE_ID CHAR(36) NOT NULL,
    GROUP_KEY CHAR(36) NOT NULL,
    CREATED_DATE BIGINT NOT NULL,
    MESSAGE_PRIORITY BIGINT,
    MESSAGE_SEQUENCE BIGINT NOT NULL DEFAULT nextval('INT_MESSAGE_SEQ'),
    MESSAGE_BYTES BYTEA,
    REGION VARCHAR(100) NOT NULL,
    CONSTRAINT INT_CHANNEL_MESSAGE_PK PRIMARY KEY (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE INDEX IF NOT EXISTS INT_CHANNEL_MSG_DELETE_IDX ON INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_ID);

-- Metadata store table
CREATE TABLE IF NOT EXISTS INT_METADATA_STORE (
    METADATA_KEY VARCHAR(255) NOT NULL,
    METADATA_VALUE VARCHAR(4000),
    REGION VARCHAR(100) NOT NULL,
    CONSTRAINT INT_METADATA_STORE_PK PRIMARY KEY (METADATA_KEY, REGION)
);
